export const apiRoutes = {
  getBanners: "banner",
  getArticles: (page: number) => `article?page=${page}`,
  getLatestArticles: "latest-article",
  getSingleArticle: (id: string) => `article/${id}`,
  getDictionaryList: (page: number) => `dictionary?page=${page}`,
  getSingleDictionary: (id: string) => `dictionary/${id}`,
  getCoursesList: (page: number) => `course?page=${page}`,
  getSingleCourse: (id: string) => `course/${id}`,
  getCourseLessons: (id: string) => `lesson?course_id=${id}`,
  getSingleLesson: (id: string) => `lesson/${id}`,
  getSettingsKeys: "settings",
  getSingleSettingsKey: (key: string) => `settings/${key}`,
  getPlans: "plans",
  getLiveEvents: "live-events",
  showEventInfo: (id: string) => `live-events/${id}`,
  search: (keyword: string) => `search?keyword=${keyword}`,
  contactUs: "contactUs", // post (email,name,message) required, (files) optional
};

export const authRoutes = {
  register: "register",
  login: "login",
  logout: "logout",
  updateProfile: "update-profile",
  getProfile: "profile",
  sendPasswordReminder: "password/remind",
  passwordReset: "password/reset",
  verifyToken: "password/verify",
  getMyCourses: "myCourses",
  getMyDictionary: "myDictionary",
  freeCourseSubscription: "freeCourseSubscription",
  paidCourseSubscription: "paidCourseSubscription",
  buyDictionary: "dictionary/buy",
  viewLesson: (lessonId: string) => `lesson/view/${lessonId}`,
  completeLesson: (lessonId: string) => `lesson/complete/${lessonId}`,
  courseBookmark: (id: string) => `/course/bookmark/${id}`,
  articleBookmark: (id: string) => `/article/bookmark/${id}`,
  lessonBookmark: (id: string) => `/lesson/bookmark/${id}`,
  dictionaryBookmark: (id: string) => `/dictionary/bookmark/${id}`,
  buyPlan: `plans/buy`,
  buyLiveEvent: `live-events/buy`,
  getCertificates: "certificates",
  getNotifications: "notifications",
  markAsReadNotification: (notificationId: string) =>
    `notifications/mark-as-read/${notificationId}`,
  markAllAsReadNotifications: `notifications/mark-all-as-read`,
  registerDeviceToken: "register-device", // post (device_token)
  getBookmarkedCourse: "bookmarked/course",
  getBookmarkedLesson: "bookmarked/lesson",
  getBookmarkedArticle: "bookmarked/article",
  getBookamrkedDictionary: "bookmarked/dictionary",
  getMyPlans: "myPlans",
  getLiveSupportStatus: "live-support-status",
  showLiveSupport: (id: number) => `live-support/${id}`,
  createLiveSupportRequest: "live-support", // post
  deleteAccount: "deleteAccount",
};
